### ISSUE TITLE
Steps used to create image?

### ISSUE THREAD

**Issue by amilajack** [mattdesl/baboon-image-uri#1]
I am trying to to generate a data uri from an image that I have. I'm wondering how this the uri for this image was generated. Did you use a plugin or something of the sort?

**Comment by mattdesl** [comment]
There's a lot of npm modules that can do this – here's one of them:
https://github.com/mattdesl/urify

e.g. if you run the following script in node, after `npm install urify --save`, it will print a base64 datauri to stdout:

``` js
var uri = require('urify')('image.png');
console.log(uri);
```

**Comment by amilajack** [comment]
Thanks!
